import FormModal from 'flarum/common/components/FormModal';
import Stream from 'flarum/common/utils/Stream';
import type Mithril from 'mithril';
import type HeadItem from '../model/HeadItem';
type LinkAs = '' | 'style' | 'script' | 'font' | 'image' | 'fetch' | 'worker';
type FetchPriority = '' | 'high' | 'low' | 'auto';
export default class HeaderModal extends FormModal {
    item: HeadItem;
    description: ReturnType<typeof Stream<string>>;
    type: ReturnType<typeof Stream<string>>;
    location: ReturnType<typeof Stream<string>>;
    pages: ReturnType<typeof Stream<string[]>>;
    metaNameMode: ReturnType<typeof Stream<'name' | 'property'>>;
    metaName: ReturnType<typeof Stream<string>>;
    metaProperty: ReturnType<typeof Stream<string>>;
    metaContent: ReturnType<typeof Stream<string>>;
    linkRel: ReturnType<typeof Stream<string>>;
    linkHref: ReturnType<typeof Stream<string>>;
    linkAs: ReturnType<typeof Stream<LinkAs>>;
    linkType: ReturnType<typeof Stream<string>>;
    linkCrossorigin: ReturnType<typeof Stream<boolean>>;
    linkFetchpriority: ReturnType<typeof Stream<FetchPriority>>;
    linkExtras: ReturnType<typeof Stream<Array<{
        key: string;
        value: string;
    }>>>;
    scriptMode: ReturnType<typeof Stream<'src' | 'inline'>>;
    scriptSrc: ReturnType<typeof Stream<string>>;
    scriptInline: ReturnType<typeof Stream<string>>;
    scriptDefer: ReturnType<typeof Stream<boolean>>;
    scriptAsync: ReturnType<typeof Stream<boolean>>;
    scriptModule: ReturnType<typeof Stream<boolean>>;
    scriptCrossorigin: ReturnType<typeof Stream<boolean>>;
    styleInline: ReturnType<typeof Stream<string>>;
    rawContent: ReturnType<typeof Stream<string>>;
    oninit(vnode: Mithril.Vnode): void;
    className(): string;
    title(): string | any[];
    buildPreviewHtml(): string;
    helpText(key: string): JSX.Element;
    renderPreviewBlock(): JSX.Element;
    content(): JSX.Element;
    renderMetaFields(): JSX.Element;
    renderLinkFields(): JSX.Element;
    renderScriptFields(): JSX.Element;
    renderStyleFields(): JSX.Element;
    renderRawFields(): JSX.Element;
    buildAttributes(): Record<string, unknown>;
    onsubmit(e: SubmitEvent): void;
}
export {};
